version: '2.1'

services:

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: stockdata
    ports:
      - 5434:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data