spring:
  application:
    name: chart-generator
  main:
    banner-mode: off
  kafka:
    listener:
      missing-topics-fatal: false
    bootstrap-servers: kafka:9092

bde:
  stock-analysis:
    list-of-stocks: BTC
    image-generator:
      output-dir: /home/justin/Desktop/StockImages/
    datasource:
      url: jdbc:postgresql://${DB_HOST}:${DB_TCP_5432}/${DB_NAME:stockdata}
      username: ${DB_USERNAME:dev}
      password: ${DB_PASSWORD:dev}
      driver-class-name: org.postgresql.Driver